                                                                                             docker-compose.yaml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: avs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Suraj_jadhav2003
      MYSQL_DATABASE: users
    ports:
      - "3306:3306"
    volumes:
      - ./setup_database_updated.sql:/docker-entrypoint-initdb.d/setup_database_updated.sql
      - mysql_data:/var/lib/mysql

  
  app:
    build: .
    container_name: avs_app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Suraj_jadhav2003
      - DB_NAME=users

volumes:
  mysql_data:




